"""Build deliverables/PRISM_Book.pdf — the illustrated, multi-level book.

Textbook register: every chapter opens with an "In plain terms" box an
undergraduate can follow, the body carries the full technical content,
and "For researchers" notes hold the graduate-level caveats. All data
figures come from deliverables/book_figures/ (generated by
build_book_figures.py from the committed experiment CSVs).
"""

import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (BaseDocTemplate, Frame, Image,
                                NextPageTemplate, PageBreak, PageTemplate,
                                Paragraph, Spacer, Table, TableStyle)

ROOT = os.path.join(os.path.dirname(__file__), "..")
FIG = os.path.join(ROOT, "deliverables", "book_figures")
OUT = os.path.join(ROOT, "deliverables", "PRISM_Book.pdf")

INK = colors.HexColor("#222222")
MUT = colors.HexColor("#666460")
BLUE = colors.HexColor("#2a78d6")
BOXBG = colors.HexColor("#eef4fc")
NOTEBG = colors.HexColor("#f7f4ec")
THMBG = colors.HexColor("#f0f7f1")

S = {
    "cover_t": ParagraphStyle("ct", fontName="Times-Bold", fontSize=30,
                              leading=36, textColor=INK),
    "cover_s": ParagraphStyle("cs", fontName="Times-Roman", fontSize=13,
                              leading=18, textColor=MUT),
    "h1": ParagraphStyle("h1", fontName="Times-Bold", fontSize=19,
                         leading=23, spaceBefore=8, spaceAfter=8,
                         textColor=BLUE),
    "h2": ParagraphStyle("h2", fontName="Times-Bold", fontSize=13,
                         leading=16, spaceBefore=10, spaceAfter=4,
                         textColor=INK),
    "body": ParagraphStyle("b", fontName="Times-Roman", fontSize=10.5,
                           leading=14.5, spaceAfter=6, textColor=INK),
    "box": ParagraphStyle("bx", fontName="Helvetica", fontSize=9.5,
                          leading=13.5, textColor=INK),
    "boxtitle": ParagraphStyle("bt", fontName="Helvetica-Bold",
                               fontSize=9, textColor=BLUE,
                               spaceAfter=3),
    "notetitle": ParagraphStyle("nt", fontName="Helvetica-Bold",
                                fontSize=9,
                                textColor=colors.HexColor("#8a6d1d"),
                                spaceAfter=3),
    "thmtitle": ParagraphStyle("tt", fontName="Helvetica-Bold",
                               fontSize=9,
                               textColor=colors.HexColor("#1e6b2e"),
                               spaceAfter=3),
    "cap": ParagraphStyle("cap", fontName="Helvetica-Oblique",
                          fontSize=8.5, leading=11, textColor=MUT,
                          spaceBefore=3, spaceAfter=10),
    "toc": ParagraphStyle("toc", fontName="Times-Roman", fontSize=11.5,
                          leading=20, textColor=INK),
    "tcell": ParagraphStyle("tc", fontName="Helvetica", fontSize=8.5,
                            leading=11, textColor=INK),
}


def boxed(title, text, bg, tstyle):
    inner = [Paragraph(title, tstyle), Paragraph(text, S["box"])]
    t = Table([[inner]], colWidths=[16.2 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8d5cc")),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [Spacer(1, 4), t, Spacer(1, 8)]


def plain(text):
    return boxed("IN PLAIN TERMS", text, BOXBG, S["boxtitle"])


def note(text):
    return boxed("FOR RESEARCHERS", text, NOTEBG, S["notetitle"])


def theorem(title, text):
    return boxed(title, text, THMBG, S["thmtitle"])


def fig(name, caption, width=15.5):
    img = Image(os.path.join(FIG, name))
    ratio = img.imageHeight / img.imageWidth
    img.drawWidth = width * cm
    img.drawHeight = width * ratio * cm
    return [Spacer(1, 6), img, Paragraph(caption, S["cap"])]


def P(text):
    return Paragraph(text, S["body"])


story = []

# ================= COVER =================
story += [Spacer(1, 4.5 * cm),
          Paragraph("PRISM", S["cover_t"]),
          Paragraph("Ordering as a Search Space", ParagraphStyle(
              "st", parent=S["cover_t"], fontSize=18, leading=24,
              textColor=MUT)),
          Spacer(1, 1 * cm),
          Paragraph("The Permutation-based Reasoning and Intelligence "
                    "Search Method — theory, honest experiments, failure "
                    "maps, and a real application, from first principles "
                    "to research frontier.", S["cover_s"]),
          Spacer(1, 8 * cm),
          Paragraph("Blessings Mambwe · with autonomous research "
                    "execution by Claude", S["cover_s"]),
          Paragraph("Version 1.0 · July 2026 · "
                    "github.com/bleymambwe/PRISM (tags iteration-02…09)",
                    S["cover_s"]),
          PageBreak()]

# ================= TOC =================
story += [Paragraph("Contents", S["h1"])]
toc = [
    "1 &nbsp; The Idea: Order Is a Search Space",
    "2 &nbsp; The Algorithm",
    "3 &nbsp; The Theory — and What It Does Not Promise",
    "4 &nbsp; Honest Benchmarks: Ground Truth by Construction",
    "5 &nbsp; Operators Must Match Landscapes (and How to Automate It)",
    "6 &nbsp; When Search Beats Randomness: the Locality Diagnostic",
    "7 &nbsp; Application: Ordering an LLM's Reasoning Steps",
    "8 &nbsp; Doing Research Cheaply: Infrastructure and Costs",
    "9 &nbsp; Critique, Limitations, and Open Problems",
    "Appendix: Experiment Ledger and Reproduction Guide",
]
for t in toc:
    story.append(Paragraph(t, S["toc"]))
story.append(PageBreak())

# ================= CH 1 =================
story += [Paragraph("1 · The Idea: Order Is a Search Space", S["h1"])]
story += plain(
    "You have five building blocks and you must use all five. The only "
    "choice is the order to stack them — and it turns out the order can "
    "be the difference between a system that works perfectly and one "
    "that fails completely. PRISM is an algorithm that searches over "
    "orderings. This book explains how it works, proves when it must "
    "succeed, shows — with unusually honest experiments — when it "
    "fails, and ends with a striking real-world result: reordering six "
    "instructions in an AI prompt swings its math accuracy from 6% to "
    "97%.")
story += [P(
    "Many systems consist of fixed components applied in sequence: "
    "layers in a neural network, optimization passes in a compiler, "
    "topics in a curriculum, options in a robot's plan, reasoning steps "
    "in a language-model prompt. Classical design tunes <i>which</i> "
    "components to use. PRISM asks the narrower question: given fixed "
    "components, <i>in what order</i>? Formally, a candidate solution "
    "is a permutation &pi; of n items, the search space is the "
    "symmetric group S<sub>n</sub> of size n! (already 3.6 million at "
    "n = 10), and the goal is to maximize a task-specific fitness "
    "F(&pi;).")]
story += fig("fig_concept.png",
             "Figure 1.1 — The entire idea in one picture: the same five "
             "blocks in two orders. On the real benchmarks of Chapter 4, "
             "ordering alone separates perfect accuracy from coin-flipping.")
story += note(
    "Why permutations rather than general architecture search? The "
    "constraint that every component appears exactly once keeps the "
    "space finite and highly structured (a Cayley graph under any move "
    "set), which is what makes the convergence theory of Chapter 3 and "
    "the exact-enumeration methodology of Chapter 4 possible. The cost "
    "is expressiveness: PRISM does not add, remove, or modify "
    "components. Everything in this book is conditional on that scope.")
story.append(PageBreak())

# ================= CH 2 =================
story += [Paragraph("2 · The Algorithm", S["h1"])]
story += plain(
    "PRISM is evolution in miniature. Keep twenty candidate orderings. "
    "Score each one. Always keep the best (so progress is never lost). "
    "Fill the rest of the next generation by picking three candidates "
    "at random, keeping the best of the three, copying it, and "
    "occasionally shuffling the copy a little. Repeat.")
story += fig("fig_loop.png",
             "Figure 2.1 — One generation of PRISM. The loop's four "
             "defaults: population 20, tournament size 3, mutation "
             "probability 0.05 per child, elitism 1.")
story += [Paragraph("2.1 The mutation operators", S["h2"]), P(
    "How a copy is 'shuffled a little' turns out to be the single most "
    "consequential design choice in the whole framework (Chapter 5). "
    "Four operators are implemented: <b>swap</b> exchanges two "
    "positions; <b>insert</b> removes one element and re-inserts it "
    "elsewhere; <b>inversion</b> reverses a contiguous segment; "
    "<b>scramble</b> shuffles a segment. Two meta-modes remove the "
    "choice: <b>portfolio</b> draws one of the four uniformly at random "
    "per mutation event, and <b>adaptive</b> learns operator weights "
    "from which mutations improve their parent."),
    Paragraph("2.2 Versioning discipline", S["h2"]), P(
    "Every algorithm version is a git tag (iteration-02 through "
    "iteration-09), and each version reproduces the previous one "
    "bit-for-bit under equal seeds when run with default parameters — "
    "so every historical result in this book remains exactly "
    "reproducible from its tag.")]
story.append(PageBreak())

# ================= CH 3 =================
story += [Paragraph("3 · The Theory — and What It Does Not Promise",
                    S["h1"])]
story += plain(
    "Two mathematical facts power PRISM. First: because mutation can "
    "always eventually produce any ordering, no ordering is ever "
    "permanently out of reach. Second: because the best candidate is "
    "always kept, once the search finds a best-possible ordering it can "
    "never lose it. Together these guarantee the search ends up at an "
    "optimal ordering — eventually. The fine print of 'eventually' is "
    "where the real science lives.")
story += theorem(
    "CONVERGENCE (Markov-chain absorption)",
    "Model each population as a state of a finite Markov chain. With "
    "mutation probability p<sub>m</sub> &gt; 0 the chain is "
    "irreducible; with elitism &ge; 1, populations containing a global "
    "optimum form an absorbing set. Hence Pr(the population eventually "
    "contains an optimum) = 1.")
story += theorem(
    "RUNTIME (project claim, empirically supported in-range)",
    "Under the project's stated assumptions, the expected number of "
    "generations to first reach an optimum is O(n³ log n). Measured "
    "hitting times on structured landscapes are consistent with this "
    "shape out to n = 16 (log-log exponents 2.79–3.44 for matched "
    "operators; the ratio E[T]/(n³ ln n) is flat across a threefold "
    "range of n).")
story += fig("fig_scaling.png",
             "Figure 3.1 — Measured mean hitting times (15 seeds) versus "
             "the theoretical n³ log n shape, from the Iteration-2 "
             "scaling study.")
story += note(
    "Convergence-with-probability-1 is cheap: essentially any elitist "
    "algorithm with nonzero mutation has it (Rudolph 1994), including "
    "random search with memory. The scientifically falsifiable content "
    "is the runtime, and the experiments of Chapters 5–6 map exactly "
    "when the polynomial-time behavior holds: it requires (a) a "
    "mutation operator matched to the landscape type and (b) a "
    "landscape whose top end has exploitable locality. Deceptive "
    "landscapes defeat every operator (Chapter 6) while leaving the "
    "convergence guarantee technically true and practically useless.")
story.append(PageBreak())

# ================= CH 4 =================
story += [Paragraph("4 · Honest Benchmarks: Ground Truth by Construction",
                    S["h1"])]
story += plain(
    "Early versions of this research fooled themselves twice: their "
    "test networks ignored part of the ordering, and randomness in "
    "training meant a lucky run could look like a discovery. The fix: "
    "make every position matter, make each ordering's score perfectly "
    "repeatable by deriving the randomness from the ordering itself, "
    "and then simply evaluate EVERY possible ordering — so the true "
    "best answer is known and the search can be graded like an exam "
    "with an answer key.")
story += [P(
    "The v4 benchmark design stacks n permuted <i>residual</i> "
    "bottleneck blocks (residual connections keep every ordering "
    "trainable — a plain deep stack fails, an instructive falsified "
    "redesign). Weight initialization is seeded from the permutation, "
    "and fitness is the mean of k = 3 trials: the same ordering always "
    "scores identically. Determinism makes full enumeration meaningful: "
    "120 orderings at n = 5, 720 at n = 6, 5040 at n = 7 — each "
    "landscape evaluated exhaustively.")]
story += fig("fig_landscapes.png",
             "Figure 4.1 — Three fully enumerated fitness landscapes. "
             "Dashed line: the global optimum. Search quality can now be "
             "reported as an exact hit rate and regret: 100% at n=5 XOR, "
             "90% at n=6, and the instructive n=7 story of Chapter 6.")
story += note(
    "An accidental robustness check: a process overlap re-evaluated 103 "
    "permutations in separate runs — every value matched exactly. "
    "Protocol details that matter: best-ever fitness under stochastic "
    "evaluation is inflated by selection bias (the original benchmarks' "
    "\"100% accuracy\" was partly this); a variance gate should precede "
    "any expensive study (an objective whose optimum set is dense, like "
    "n=7 XOR at k=1, cannot discriminate between search methods at any "
    "budget).")
story.append(PageBreak())

# ================= CH 5 =================
story += [Paragraph("5 · Operators Must Match Landscapes "
                    "(and How to Automate It)", S["h1"])]
story += plain(
    "Different puzzles need different kinds of shuffling. If exact "
    "positions matter, swap two items. If what matters is what comes "
    "before what, slide an item to a new place. If neighbors matter — "
    "like cities on a route — flip a whole section. Get this wrong and "
    "the search does not merely slow down: on hard landscapes it fails "
    "completely, every single time. The fix is disarmingly simple: mix "
    "all the shuffles and pick one at random each time.")
story += [P(
    "Following the permutation-EA literature (Cicirello's A/R/P "
    "classification), each landscape type has a matched operator: "
    "swap for absolute-position structure, insert for precedence, "
    "inversion for adjacency. Iteration 3 tested all four operators on "
    "all three types (n = 6–16, 15 seeds): the matched operator won on "
    "every type, and on plateau-rich landscapes every mismatched "
    "operator hit the 10,000-generation failure cap on 100% of runs — "
    "problems the matched operator solves in a few hundred "
    "generations.")]
story += fig("fig_operators.png",
             "Figure 5.1 — The operator-matching result. Bold line: the "
             "literature-matched operator. Lines that climb into the cap "
             "are total failures, not slowdowns.")
story += [P(
    "The <b>portfolio</b> (uniform random operator per mutation event) "
    "removes the choice: zero failures on every landscape at every "
    "size, at only 1.1–4.1× the matched operator's cost — a bounded "
    "insurance premium against an unbounded downside. The adaptive "
    "variant correctly identifies the matched operator on every "
    "landscape (a useful diagnostic) but does not beat the uniform "
    "portfolio: its reward signal (~1 mutation event per generation) "
    "is too sparse.")]
story += fig("fig_portfolio.png",
             "Figure 5.2 — Matched operator vs portfolio at n = 16. The "
             "dashed line marks where every mismatched fixed operator "
             "sits: total failure.")
story.append(PageBreak())

# ================= CH 6 =================
story += [Paragraph("6 · When Search Beats Randomness: "
                    "the Locality Diagnostic", S["h1"])]
story += plain(
    "Here is the chapter most books would hide. On one of our own "
    "benchmarks — the fully enumerated n = 7 neural landscape — PRISM "
    "turned out to be no better than picking orderings at random. Why? "
    "Evolution works by taking small steps from good solutions to "
    "better ones. That only helps if 'near a good solution' tends to "
    "be good. We then found two numbers, computable BEFORE running any "
    "search, that predict exactly when that is true.")
story += [P(
    "Experiment I (n = 7 parity, evaluations-to-first-optimum, random "
    "baseline): default PRISM prematurely converges (4/15 hits, "
    "exploring ~103 distinct orderings — statistically identical to "
    "random at that budget); tuned PRISM (pop 40, p<sub>m</sub> 0.6) "
    "hits 15/15 but needs 384 mean evaluations versus random's 318; "
    "random matches or beats PRISM's best-found quality at every "
    "budget &ge; 50. The governing variable is <b>landscape "
    "locality</b>, and two classical statistics measure it: "
    "&rho;<sub>1</sub>, the correlation between an ordering's fitness "
    "and its one-move neighbor's fitness; and FDC, the correlation "
    "between fitness and distance to the nearest optimum.")]
story += fig("fig_locality.png",
             "Figure 6.1 — The locality diagnostic across all eight "
             "enumerated landscapes. Left: ρ1 per operator recovers the "
             "matched operator (row-wise maximum) on 3/3 typed synthetic "
             "landscapes; the neural landscapes are near-zero — locally "
             "almost random. Right: FDC separates every observed outcome "
             "— strongly negative = search pays; near zero = needle in a "
             "haystack (PRISM ≈ random); positive = deceptive (smooth "
             "but pointing away — do not use PRISM).")
story += theorem(
    "THE PRE-FLIGHT RULE (Decision D14)",
    "Before applying PRISM to any new problem: sample a few hundred "
    "evaluations; compute ρ1 per operator and FDC. Use argmax ρ1 "
    "(excluding scramble, whose ρ1 is inflated by identity moves) as "
    "the operator. Proceed with evolutionary search only if FDC is "
    "materially negative; if it is near zero, random sampling is the "
    "honest method of record; if positive, PRISM is the wrong tool.")
story.append(PageBreak())

# ================= CH 7 =================
story += [Paragraph("7 · Application: Ordering an LLM's Reasoning Steps",
                    S["h1"])]
story += plain(
    "Take six sensible instructions for solving a math problem — "
    "restate it, list the knowns, make a plan, do the calculation, "
    "check the result, state the answer — and give them to an AI model "
    "as numbered steps. Does the order of the instructions matter? "
    "Enormously: the same model on the same questions scores 6% with "
    "the worst ordering and 97% with the best. And the two numbers "
    "from Chapter 6, computed first, correctly predicted both which "
    "shuffle to use and that the search would beat random guessing.")
story += [P(
    "All 720 orderings of the six modules were enumerated exactly "
    "(Gemini 2.5 Flash-Lite, temperature 0, a fixed 32-question GSM8K "
    "subset; ~23,000 cached API calls, ≈$3–5). The position-effect "
    "table is directly usable prompt-engineering guidance: the "
    "answer-format instruction placed first drops mean accuracy to "
    "0.435 (the model answers before reasoning) versus 0.870 last; the "
    "compute instruction placed first yields 0.908 (calculate early, "
    "verify later).")]
story += fig("fig_llm.png",
             "Figure 7.1 — Left: mean accuracy when each module sits at "
             "each prompt position. Right: the full enumerated landscape "
             "— ordering alone spans 6.3% to 96.9% accuracy.")
story += [P(
    "The D14 pre-flight predicted the experiment before any search "
    "ran: ρ1 selected <b>insert</b> (0.547) — exactly the operator "
    "theory's prediction for precedence-type problems — and "
    "FDC = −0.346 predicted that search beats random. Both held: PRISM "
    "reached an exactly optimal ordering in a mean of 6 distinct "
    "evaluations versus 18 for random (15/15 seeds). Honest caveat: "
    "optima are moderately dense here (60/720), so random remains "
    "respectable; sparser, harder instances are the natural stress "
    "test.")]
story.append(PageBreak())

# ================= CH 8 =================
story += [Paragraph("8 · Doing Research Cheaply: Infrastructure and "
                    "Costs", S["h1"])]
story += plain(
    "This entire research program — eleven experiments, nine algorithm "
    "versions, tens of thousands of evaluations — cost less than six "
    "dollars, all of it API fees. The trick is designing experiments "
    "small enough to enumerate, caching every paid evaluation so it is "
    "paid exactly once, and writing every long-running job so it can "
    "be killed at any moment and resume without losing work.")
story += [P(
    "Three patterns carried the program. <b>Budgeted-resumable "
    "runners</b>: every experiment appends results incrementally, "
    "accepts a wall-clock budget, and resumes by key — a pattern forced "
    "by a machine that kills long processes, and exactly the behavior "
    "cloud spot instances reward. <b>Evaluation caches</b>: for "
    "API-priced fitness (Chapter 7), a per-(ordering, question) answer "
    "cache makes enumeration, search, and all analyses draw from one "
    "paid pass. <b>Free analysis</b>: once a landscape is enumerated, "
    "every further question — hyperparameter sweeps, baselines, "
    "locality statistics — costs nothing. On Google Cloud the full "
    "program would have cost ≈$1 of compute (e2-standard-4) plus API "
    "fees; the near-term roadmap totals under $10 on-demand, and its "
    "one expensive item (a CIFAR-10 GPU run) is $0 on Kaggle's free "
    "tier.")]
story.append(PageBreak())

# ================= CH 9 =================
story += [Paragraph("9 · Critique, Limitations, and Open Problems",
                    S["h1"])]
story += plain(
    "A good research program keeps a list of the ways it might be "
    "wrong. Ours: the problems are still small; the guarantee "
    "everyone quotes is the cheap part of the theory; the operator "
    "result confirms known literature more than it invents; and on "
    "landscapes without local structure, honest measurement shows "
    "plain random guessing is just as good.")
story += [P(
    "<b>Scale.</b> Everything enumerable tops out at n = 7 (5040 "
    "orderings). The methodology transfers to larger n via sampled "
    "pre-flights and regret-versus-best-known, but no result yet "
    "demonstrates it. <b>Theory.</b> The runtime bound's assumptions "
    "need primary-source verification; the falsifiable frontier is "
    "characterizing exactly which landscape classes admit the "
    "polynomial behavior. <b>Hyperparameters.</b> Defaults are "
    "n ≤ 6 settings; scale-aware settings (pop ≥ 40, p<sub>m</sub> ≥ "
    "0.5 at n = 7) are empirical, not principled. <b>Applications.</b> "
    "One validated application exists; its optima were dense. The "
    "sharpest open problems: adaptive operator selection that actually "
    "beats the uniform portfolio given ~1 reward event per generation; "
    "mixed-type landscapes; sampling-error bounds for the pre-flight "
    "statistics; and whether the locality diagnostic's predictions "
    "survive on problems where enumeration is impossible and ground "
    "truth is never known.")]
story += [Paragraph("The honest pitch", S["h2"]), P(
    "PRISM is not a claim that evolution beats everything. It is a "
    "small, analyzable ordering optimizer whose failure modes are "
    "mapped as carefully as its successes, shipped with a benchmark "
    "methodology (exact enumeration, seeded determinism, mandatory "
    "random baselines) and a two-number pre-flight that tells you — "
    "before you spend anything — which operator to use and whether to "
    "use it at all. That combination, more than the algorithm itself, "
    "is the contribution.")]
story.append(PageBreak())

# ================= APPENDIX =================
story += [Paragraph("Appendix · Experiment Ledger and Reproduction",
                    S["h1"])]
rows = [["Exp", "It.", "Question", "Verdict"],
        ["A", "2", "Do historical results reproduce?",
         "Yes — plus 3 corrections"],
        ["B", "2", "Hitting time ~ n³ log n?", "Consistent (n=4–12)"],
        ["C", "3", "Matched operators win per landscape?",
         "Confirmed 3/3; mismatch = hard failure"],
        ["D", "3", "Deceptive landscapes break runtime?", "Confirmed"],
        ["E", "3", "Depth makes all positions matter?",
         "Falsified — untrainable"],
        ["F", "4", "Portfolio succeeds everywhere ≤4×?",
         "Confirmed; adaptive learns but no speedup"],
        ["G", "5", "v4: deterministic, enumerable, order-sensitive?",
         "Confirmed; hit rate 100%/40% vs exact optima"],
        ["H", "6", "Ground truth scales to n=6? n=7 (k=1)?",
         "Yes (0.90) / saturated — protocol lesson"],
        ["I", "7", "PRISM vs random, evals-to-optimum, n=7?",
         "Falsified — PRISM ≈ random here"],
        ["J", "8", "Do ρ1/FDC predict outcomes?",
         "Confirmed 8/8 landscapes; D14 adopted"],
        ["K", "9", "LLM chain ordering (GSM8K)?",
         "6%→97% by order; pre-flight predicted all"]]
t = Table([[Paragraph(c, S["tcell"]) for c in r] for r in rows],
          colWidths=[1.2 * cm, 1 * cm, 7.4 * cm, 6.6 * cm])
t.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eef8")),
    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d8d5cc")),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ("TOPPADDING", (0, 0), (-1, -1), 3),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
story += [t, Spacer(1, 12), Paragraph("Reproduction", S["h2"]), P(
    "git clone github.com/bleymambwe/PRISM — every version is a tag; "
    "every experiment is a budgeted-resumable script under "
    "experiments/iteration-0X/ (rerun with a seconds budget until "
    "'STUDY COMPLETE'); every figure in this book regenerates from the "
    "committed CSVs via scripts/build_book_figures.py; this book "
    "rebuilds via scripts/build_prism_book.py. Lab logs live in "
    "iterations/, the living handover in docs/HANDOVER.md, and the "
    "consolidated narrative in research-v2.md.")]


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUT)
    if doc.page > 1:
        canvas.drawString(2 * cm, 1.1 * cm, "PRISM · Ordering as a "
                                            "Search Space")
        canvas.drawRightString(19 * cm, 1.1 * cm, str(doc.page))
    canvas.restoreState()


doc = BaseDocTemplate(OUT, pagesize=A4, leftMargin=2 * cm,
                      rightMargin=2 * cm, topMargin=1.8 * cm,
                      bottomMargin=1.8 * cm)
frame = Frame(2 * cm, 1.8 * cm, 17 * cm, 26 * cm, id="f")
doc.addPageTemplates([PageTemplate(id="p", frames=[frame],
                                   onPage=on_page)])
doc.build(story)
print("Wrote", OUT)
